In [9]:
import pandas as pd
import numpy as np

In [10]:
v12 = pd.read_excel("Volunteers 1.1.12-12.31.12.xlsx")
v14 = pd.read_excel("Volunteers 1.1.14-12.31.14.xlsx")

In [11]:
v12.columns = v12.columns.str.replace(' ', '_')
v14.columns = v14.columns.str.replace(' ', '_')

In [12]:
VolunteerInternational = []

In [13]:
v14.International_Name.unique()

array([nan, u'AFGE', u'AFGWU', u'AFM', u'AFSA', u'AFSCME', u'AFT', u'APWU',
       u'ARA', u'ATU', u'AWIU', u'BAC', u'BCTGM', u'BRS', u'CWA', u'DALU',
       u'GMP', u'IAFF', u'IAM', u'IATSE', u'IBB', u'IBEW', u'IBT', u'ILA',
       u'IRONWORKERS', u'IUEC', u'IUOE', u'IUPA', u'IUPAT', u'LIUNA',
       u'NALC', u'NATCA', u'NNU', u'NPMHU', u'OPCMIA', u'OPEIU',
       u'ROOFERS', u'SEIU', u'SMWIA', u'TWU', u'UA', u'UAW', u'UFCW',
       u'UMWA', u'UNITE-HERE', u'USW', u'UTU', u'UWUA', u'WA'], dtype=object)

In [16]:
int_longname = v14.replace({'International_Name' : { 'AFGE' : 'GOVERNMENT WORKERS', 'AFGWU' : 'GLASS WORKERS, FLINT', 'AFM' : 'MUSICIANS', 'AFSA' : 'SCHOOL ADMINISTRATORS', 
                                     'AFSCME' : 'STATE, COUNTY & MUNICIPAL EMPLOYEES', 'AFT' : 'TEACHERS','APWU' : 'POSTAL WORKERS', 'ARA' : 'ALLIANCE FOR RETIRED AMERICANS', 
                                     'ATU' : 'AMALGAMATED TRANSIT', 'AWIU' : 'HEAT & FROST INSULATORS', 'BAC' : 'BRICKLAYERS', 'BCTGM' : 'BAKERY WORKERS',
                                    'BRS' : 'SIGNALMAN, RAILROAD', 'CWA' : 'COMMUNICATIONS WORKERS', 'DALU' : 'DIRECTLY AFFILIATED UNIONS', 'GMP' : 'GLASS, MOLDERS, POTTERY', 
                                     'IAFF' : 'FIRE FIGHTERS', 'IAM' : 'MACHINISTS', 'IATSE' : 'STAGE EMPLOYEES', 'IBB' : 'BOILERMAKERS',
                                     'IBEW' : 'ELECTRICAL WORKERS', 'IBT' : 'TEAMSTERS', 'ILA' : 'LONGSHOREMAN', 'IRONWORKERS' : 'IRON WORKERS',
                                    'IUEC' : 'ELEVATOR CONSTRUCTORS', 'IUOE' : 'ENGINEERS, OPERATING', 'IUPA' : 'POLICE ASSOCIATION', 'IUPAT' : 'PAINTERS', 'LIUNA' : 'LABORERS',
                                    'NALC' : 'LETTER CARRIERS', 'NATCA' : 'AIR TRAFFIC CONTROLLERS', 'NNU' : 'NATIONAL NURSES UNITED', 'NPMHU' : 'MAIL HANDLERS', 
                                     'OPCMIA' : 'PLASTERERS', 'OPEIU' : 'OFFICE & PROFESSIONAL', 'SEIU' : 'SERVICE EMPLOYEES',
                                     'SMWIA' : 'SHEET METAL WORKERS', 'TWU' : 'TRANSPORT WORKERS', 'UA' : 'PLUMBERS & PIPEFITTERS', 'UAW' : 'AUTO WORKERS',
                                    'UFCW' : 'FOOD AND COMMERCIAL', 'UMWA' : 'MINE WORKERS', 'USW' : 'STEELWORKERS',
                                     'UTU' : 'UNITED TRANSPORTATION UNION', 'UWUA' : 'UTILITY WORKERS', 'WA' : 'WRITERS GUILD'}})




In [17]:
int_longname.International_Name.unique()

array([nan, 'GOVERNMENT WORKERS', 'GLASS WORKERS, FLINT', 'MUSICIANS',
       'SCHOOL ADMINISTRATORS', 'STATE, COUNTY & MUNICIPAL EMPLOYEES',
       'TEACHERS', 'POSTAL WORKERS', 'ALLIANCE FOR RETIRED AMERICANS',
       'AMALGAMATED TRANSIT', 'HEAT & FROST INSULATORS', 'BRICKLAYERS',
       'BAKERY WORKERS', 'SIGNALMAN, RAILROAD', 'COMMUNICATIONS WORKERS',
       'DIRECTLY AFFILIATED UNIONS', 'GLASS, MOLDERS, POTTERY',
       'FIRE FIGHTERS', 'MACHINISTS', 'STAGE EMPLOYEES', 'BOILERMAKERS',
       'ELECTRICAL WORKERS', 'TEAMSTERS', 'LONGSHOREMAN', 'IRON WORKERS',
       'ELEVATOR CONSTRUCTORS', 'ENGINEERS, OPERATING',
       'POLICE ASSOCIATION', 'PAINTERS', 'LABORERS', 'LETTER CARRIERS',
       'AIR TRAFFIC CONTROLLERS', 'NATIONAL NURSES UNITED',
       'MAIL HANDLERS', 'PLASTERERS', 'OFFICE & PROFESSIONAL', u'ROOFERS',
       'SERVICE EMPLOYEES', 'SHEET METAL WORKERS', 'TRANSPORT WORKERS',
       'PLUMBERS & PIPEFITTERS', 'AUTO WORKERS', 'FOOD AND COMMERCIAL',
       'MINE WORKERS', 

In [18]:
int_longname

MyCampaignID International_Name Local_Name Participant_Local  \
0         100956156                NaN        NaN               NaN   
1         103286494                NaN        NaN               NaN   
2         100016488                NaN        NaN               NaN   
3         103334925                NaN        NaN               NaN   
4         100958002                NaN        NaN               NaN   
5         100808013                NaN        NaN               NaN   
6         103327140                NaN        NaN               NaN   
7         103334925                NaN        NaN               NaN   
8         100783642                NaN        NaN               NaN   
9         101802969                NaN        NaN               NaN   
10        100905662                NaN        NaN               NaN   
11        101633212                NaN        NaN               NaN   
12        101808678                NaN        NaN               NaN   
13        101808678                NaN        NaN               NaN   
14        100823646                NaN        NaN               NaN   
15        102441047                NaN        NaN               NaN   
16        102441047                NaN        NaN               NaN   
17        100911391                NaN        NaN               NaN   
18        102441047                NaN        NaN               NaN   
19        100016950                NaN        NaN               NaN   
20        100911391                NaN        NaN               NaN   
21        102441047                NaN        NaN               NaN   
22        100016950                NaN        NaN               NaN   
23        102441047                NaN        NaN               NaN   
24        103082346                NaN        NaN               NaN   
25        103290096                NaN        NaN               NaN   
26        103290104                NaN        NaN               NaN   
27        101507797                NaN        NaN               NaN   
28        100665044                NaN        NaN               NaN   
29        100318731                NaN        NaN               NaN   
...             ...                ...        ...               ...   
34383     100376908    UTILITY WORKERS        436               NaN   
34384     100574479    UTILITY WORKERS        436               NaN   
34385     100574479    UTILITY WORKERS        436               NaN   
34386     100605710    UTILITY WORKERS        686               NaN   
34387     100605710    UTILITY WORKERS        686               NaN   
34388     100605710    UTILITY WORKERS        686               NaN   
34389     100481315    UTILITY WORKERS        999               NaN   
34390     100481315    UTILITY WORKERS        999               NaN   
34391     100481315    UTILITY WORKERS        999               NaN   
34392     100481315    UTILITY WORKERS        999               NaN   
34393     100481315    UTILITY WORKERS        999               NaN   
34394     100481315    UTILITY WORKERS        999               NaN   
34395     100481315    UTILITY WORKERS        999               NaN   
34396     103364469    UTILITY WORKERS        999               NaN   
34397     100481315    UTILITY WORKERS        999               NaN   
34398     103364469    UTILITY WORKERS        999               NaN   
34399     100481315    UTILITY WORKERS        999               NaN   
34400     103364469    UTILITY WORKERS        999               NaN   
34401     100481315    UTILITY WORKERS        999               NaN   
34402     100481315    UTILITY WORKERS        999               NaN   
34403     100481315    UTILITY WORKERS        999               NaN   
34404     100481315    UTILITY WORKERS        999               NaN   
34405     100481315    UTILITY WORKERS        999               NaN   
34406     100481315    UTILITY WORKERS        999               NaN   
34407     103364469    UTILITY 

In [19]:
v14.Participant_International.unique()

array([nan, u'Actors & Artists', u'Government Workers',
       u'State, County & Municipal Employees', u'Teachers',
       u'Alliance for Retired Americans', u'Communications Workers',
       u'Machinists', u'Iron Workers', u'Painters', u'Laborers',
       u'Letter Carriers', u'Service Employees', u'Sheet Metal Workers',
       u'Transport Workers', u'Auto Workers', u'Unite-Here', u'Musicians',
       u'Postal Workers', u'Stage Employees', u'Amalgamated Transit',
       u'Heat & Frost Insulators', u'Fire Fighters', u'Electrical Workers',
       u'Teamsters', u'Office & Professional', u'Plumbers & Pipefitters',
       u'Food And Commercial', u'Steelworkers', u'Utility Workers'], dtype=object)

In [ ]:
v14.assign(Volunteer_International = lambda x: if 'Participant_International' == Nan P(x['SepalWidth'] / x['SepalLength'])).head()